// Mengimpor tipe Metadata dari Next.js untuk mendefinisikan metadata halaman.
import type { Metadata } from "next";
// Mengimpor font Inter dari Google Fonts melalui Next.js.
import { Inter } from "next/font/google";
// Mengimpor stylesheet global untuk seluruh aplikasi.
import "./globals.css";
// Mengimpor ClerkProvider dari "@clerk/nextjs" untuk mengelola otentikasi pengguna.
import { ClerkProvider } from "@clerk/nextjs";

// Menginisialisasi font Inter dengan subset Latin.
const inter = Inter({ subsets: ["latin"] });

// Mendefinisikan metadata untuk aplikasi, termasuk title dan description.
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Mendefinisikan komponen RootLayout yang membungkus seluruh aplikasi.
// Komponen ini menerima prop children yang merupakan elemen React.
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // ClerkProvider membungkus seluruh aplikasi untuk menyediakan konteks otentikasi Clerk.
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </ClerkProvider>
  );
}
